spring:
  application:
    name: discoveryserver
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        default_schema: ${POSTGRES_DATABASE}
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${USER_NAME}:${PASSWORD}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.33
    wait-time-in-ms-when-sync-empty: 0
    peer-node-read-timeout-ms: 30000

server:
  port: 5002

