spring:
  application:
    name: discoveryserver

  datasource:
    url: jdbc:postgresql://postgresdb:5432/localdb
    username: user2711
    password: admin2711
    hikari:
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: localdb

eureka:
  instance:
    hostname: discoveryserver
    prefer-ip-address: true
    ip-address: 51.91.254.218
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin2711@discoveryserver:5002/eureka/
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    wait-time-in-ms-when-sync-empty: 5000
    peer-node-read-timeout-ms: 30000

server:
  port: 5002

logging:
  level:
    com.netflix.discovery: INFO
    org.springframework.cloud.netflix: INFO
