ACTIVE_PROFILE: test

POSTGRES_USERNAME: user2711
POSTGRES_PASSWORD: admin2711
POSTGRES_HOST: 127.0.0.1
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: admin2711
ROLES: EUREKA_CLIENT
SERVER_PORT: 5002

