spring:
  application:
    name: discoveryserver

  datasource:
    url: jdbc:postgresql://postgresdb:5432/localdb
    username: user2711
    password: admin2711
    hikari:
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        default_schema: localdb

eureka:
  instance:
    hostname: discoveryserver
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin2711@discoveryserver:5002/eureka/
  server:
    enable-self-preservation: false
    renewal-percent-threshold: 0.33
    wait-time-in-ms-when-sync-empty: 0
    peer-node-read-timeout-ms: 30000

server:
  port: 5002
