ACTIVE_PROFILE: dev

POSTGRES_USERNAME: user2711
POSTGRES_PASSWORD: admin2711
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

# this is for discovery service / eureka server
USER_NAME: admin
PASSWORD: admin2711
ROLES: EUREKA_CLIENT
SERVER_PORT: 5002

