spring:
  application:
    name: gateway
  profiles:
    active: default
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: authorization-server
            uri: lb://AUTHORIZATIONSERVER
            predicates:
              - Path=/authorization/**
          - id: user-service
            uri: lb://USERSERVICE
            predicates:
              - Path=/user/**
          - id: ebanking
            uri: lb://EBANKING
            predicates:
              - Path=/ebanking/**

          - id: notification-service
            uri: lb://NOTIFICATIONSERVICE
            predicates:
              - Path=/notification/**

          - id: ecredit-service
            uri: lb://ECREDITSERVICE
            predicates:
              - Path=/ecredit/**
            filters:
              -name: RequestRateLimiter
              args:
                rate-limiter: "#{customRateLimiter}"
                key-resolver: "#{customKeyResolver}"

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin2711@localhost:5002/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true


logging:
  level:
    com.netflix.discovery.shared.transport: TRACE
    com.netflix.discovery: TRACE
    com.netflix.discovery.shared.transport.decorator: TRACE
    org.springframework.cloud.netflix: DEBUG


server:
  port: 8000

jwks:
  uri: http://localhost:8080/oauth2/jwks
