spring:
  application:
    name: gateway

  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          #          - id: authorization-server
          #            uri: lb://AUTHORIZATIONSERVER
          #            predicates:
          #              - Path=/authorization/**
          - id: user-service
            uri: lb://USERSERVICE
            predicates:
              - Path=/user/**
          - id: ebanking
            uri: lb://EBANKING
            predicates:
              - Path=/ebanking/**
          - id: notification-service
            uri: lb://NOTIFICATIONSERVICE
            predicates:
              - Path=/notification/**
          - id: ecredit-service
            uri: lb://ECREDITSERVICE
            predicates:
              - Path=/ecredit/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin2711@discoveryserver:5002/eureka/

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix: DEBUG

server:
  port: 8000

jwks:
  uri: http://authorizationserver:8080/oauth2/jwks
