spring:
  application:
    name: gateway
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: authorization-server
            uri: lb://AUTHORIZATIONSERVER
            predicates:
              - Path=/authorization/**
          - id: user-service
            uri: lb://USERSERVICE
            predicates:
              - Path=/user/**
          - id: ebanking
            uri: lb://ebanking
            predicates:
              - Path=/ebanking/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${USER_NAME}:${PASSWORD}@localhost:5002/eureka/

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix: DEBUG


server:
  port: ${SERVER_PORT}

jwks:
  uri: ${JWKS_URI}

