ACTIVE_PROFILE: prod

PRIVATE_KEY:
PUBLIC_KEY:

POSTGRES_USER: user2711
POSTGRES_PASSWORD: admin2711
POSTGRES_HOST: 127.0.0.1
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: admin2711

SERVER_PORT: 8080

