spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
  application:
    name: authorizationserver
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: true

  datasource:
    url: jdbc:postgresql://postgresdb:5432/localdb
    username: user2711
    password: admin2711
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000

  main:
    allow-bean-definition-overriding: true

  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: localdb

eureka:
  instance:
    prefer-ip-address: true
    hostname: authorizationserver
    ip-address: 51.91.254.218
  client:
    service-url:
      defaultZone: http://admin:admin2711@discoveryserver:5002/eureka/

ui:
  app:
    url: http://51.91.254.218:4200

key:
  private: keys/private.key
  public: keys/public.key

server:
  port: 8080
  tomcat:
    max-threads: 200
    min-spare-threads: 20
