ACTIVE_PROFILE: dev

PRIVATE_KEY: "private.key"
PUBLIC_KEY: "public.key"

POSTGRES_USER: user2711
POSTGRES_PASSWORD: admin2711
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

# this is for  eureka server
USER_NAME: admin
PASSWORD: admin2711

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: douklifsa93@gmail.com
EMAIL_PASSWORD: uppv zody hnsl bbzu
VERIFY_EMAIL_HOST: http://localhost:4200

SERVER_PORT: 8086

UI_APP_URL: http://localhost:4200

JWKS_URI: http://localhost:8080/oauth2/jwks

KAFKA_SERVER_URL: localhost:9092
