ACTIVE_PROFILE: test

PRIVATE_KEY: "private.key"
PUBLIC_KEY: "public.key"

POSTGRES_USER: user2711
POSTGRES_PASSWORD: admin2711
POSTGRES_HOST: 127.0.0.1
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: admin2711

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: douklifsa93@gmail.com
EMAIL_PASSWORD: uppv zody hnsl bbzu
VERIFY_EMAIL_HOST: http://localhost:4200

SERVER_PORT: 8080

JWKS_URI: http://localhost:8080/oauth2/jwks

KAFKA_SERVER_URL: http://localhost:9092
