spring:
  application:
    name: notificationservice

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}
    default-encoding: UTF-8

  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: true
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
  main:
    allow-bean-definition-overriding: true

  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${POSTGRES_DATABASE}

  kafka:
    bootstrap-servers:
      - ${KAFKA_SERVER_URL}
    template:
      default-topic: NOTIFICATION_TOPIC
    consumer:
      group-id: topicgroupid
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # Add consumer configuration for large messages
      properties:
        fetch.message.max.bytes: 1300000000
        max.partition.fetch.bytes: 1300000000
    properties:
      spring:
        json:
          type:
            mapping: Notification:io.digiservices.notificationservice.domain.Notification
      # Add global properties for handling large messages
      fetch.message.max.bytes: 1300000000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${USER_NAME}:${PASSWORD}@localhost:5002/eureka/

ui:
  app:
    url: ${UI_APP_URL}


key:
  private: ${PRIVATE_KEY}
  public: ${PUBLIC_KEY}


server:
  port: ${SERVER_PORT}

jwks:
  uri: ${JWKS_URI}



