APPLICATION_NAME: EBANKING
APPLICATION_TITLE: DIGICRG-MICROSERVICE
APPLICATION_VERSION: v02

### Database configuration
DATABASE_HOST: 10.220.220.8
DATABASE_PORT:
DATABASE_NAME: BDCRG
DB_USERNAME: DIGI
DB_PASSWORD: @Digi2711@!
SERVER_PORT: 8089


#Active profile
ACTIVE_PROFILE: prod

JWKS_URI: http://localhost:8080/oauth2/jwks


