APPLICATION_NAME: EBANKING
APPLICATION_TITLE: DIGICRG-MICROSERVICE
APPLICATION_VERSION: v02

### Database configuration
DATABASE_HOST: 10.110.15.2
DATABASE_PORT:
DATABASE_NAME: BDCRG_TEST
DB_USERNAME: sa
DB_PASSWORD: 1234567
SERVER_PORT: 8090

#Active profile
ACTIVE_PROFILE: test

JWKS_URI: http://localhost:8080/oauth2/jwks


