APPLICATION_NAME: EBANKING
APPLICATION_TITLE: DIGICRG-MICROSERVICE
APPLICATION_VERSION: v02

# Database configuration
DATABASE_HOST: localhost
DATABASE_PORT: 1433
DATABASE_NAME: BDCRG
DB_USERNAME: sa
DB_PASSWORD: doukoure93
SERVER_PORT: 8081

#Active profile
ACTIVE_PROFILE: dev

USER_NAME: admin
PASSWORD: admin2711

JWKS_URI: http://localhost:8080/oauth2/jwks
