spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true  # Enable cache in production
  application:
    name: ecreditservice
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: true

  datasource:
    url: jdbc:postgresql://postgresdb:5432/localdb
    username: user2711
    password: admin2711
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 15  # Adjusted for production workload
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000  # 30 minutes
  main:
    allow-bean-definition-overriding: true

  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false  # Disable SQL logging in production
    hibernate:
      ddl-auto: validate  # Use validate in production to prevent schema changes
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: localdb
        # Performance optimization
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: true

  kafka:
    bootstrap-servers:
      - kafka:9092
    template:
      default-topic: NOTIFICATION_TOPIC
    producer:
      group-id: topicgroupid
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.request.size: 1300000000
        # Production Kafka settings
        acks: all
        retries: 3
        delivery.timeout.ms: 120000
        linger.ms: 5
        batch.size: 16384
        buffer.memory: 33554432
    properties:
      spring:
        json:
          type:
            mapping: Notification:io.digiservices.userservice.domain.Notification
      message.max.bytes: 1300000000
      max.request.size: 1300000000

eureka:
  instance:
    prefer-ip-address: true
    hostname: ecreditservice
    ip-address: 51.91.254.218
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://admin:admin2711@discoveryserver:5002/eureka/
    register-with-eureka: true
    fetch-registry: true

ui:
  app:
    url: http://51.91.254.218:4200

key:
  private: keys/private.key
  public: keys/public.key

server:
  port: 8085
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

jwks:
  uri: http://authorizationserver:8080/oauth2/jwks

# Logging configuration for production
logging:
  level:
    root: INFO
    io.digiservices: INFO
    org.springframework: WARN
    org.hibernate: WARN
  file:
    name: /var/log/ecreditservice/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 3GB

# Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Cache configuration
cache:
  jcache:
    config: classpath:ehcache.xml
