spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  application:
    name: ecreditservice
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: true
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/localdb
    username: user2711
    password: admin2711
    hikari:
      connection-test-query: SELECT 1
  main:
    allow-bean-definition-overriding: true

  jpa:
    database: POSTGRESQL
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: localdb

  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: NOTIFICATION_TOPIC
    producer:
      group-id: topicgroupid
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # Add producer configuration for large messages
      properties:
        max.request.size: 1300000000
    properties:
      spring:
        json:
          type:
            mapping: Notification:io.digiservices.userservice.domain.Notification
      # Add global properties for handling large messages
      message.max.bytes: 1300000000
      max.request.size: 1300000000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin2711@localhost:5002/eureka/

ui:
  app:
    url: http://localhost:4200


key:
  private: private.key
  public: public.key


server:
  port: 8087

jwks:
  uri: http://localhost:8080/oauth2/jwks
